//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Azure.ActiveDirectory.GraphClient
{
    using System;

    /// <summary>
    /// Enumeration of graph property names.
    /// </summary>
    public enum GraphProperty
    {
        /// <summary>
        /// Property None
        /// </summary>
        None = 0,

        /// <summary>
        /// Property accountEnabled
        /// </summary>
        AccountEnabled = 1,

        /// <summary>
        /// Property alternativeSecurityIds
        /// </summary>
        AlternativeSecurityIds = 2,

        /// <summary>
        /// Property appId
        /// </summary>
        AppId = 3,

        /// <summary>
        /// Property appOwnerTenantId
        /// </summary>
        AppOwnerTenantId = 4,

        /// <summary>
        /// Property approximateLastLogonTimestamp
        /// </summary>
        ApproximateLastLogonTimestamp = 5,

        /// <summary>
        /// Property assignedLicenses
        /// </summary>
        AssignedLicenses = 6,

        /// <summary>
        /// Property assignedPlans
        /// </summary>
        AssignedPlans = 7,

        /// <summary>
        /// Property associationType
        /// </summary>
        AssociationType = 8,

        /// <summary>
        /// Property authenticationPolicy
        /// </summary>
        AuthenticationPolicy = 9,

        /// <summary>
        /// Property availableToOtherTenants
        /// </summary>
        AvailableToOtherTenants = 10,

        /// <summary>
        /// Property capabilityStatus
        /// </summary>
        CapabilityStatus = 11,

        /// <summary>
        /// Property city
        /// </summary>
        City = 12,

        /// <summary>
        /// Property clientId
        /// </summary>
        ClientId = 13,

        /// <summary>
        /// Property cloudPublicIssuerCertificates
        /// </summary>
        CloudPublicIssuerCertificates = 14,

        /// <summary>
        /// Property companyLastDirSyncTime
        /// </summary>
        CompanyLastDirSyncTime = 15,

        /// <summary>
        /// Property consentType
        /// </summary>
        ConsentType = 16,

        /// <summary>
        /// Property consumedUnits
        /// </summary>
        ConsumedUnits = 17,

        /// <summary>
        /// Property country
        /// </summary>
        Country = 18,

        /// <summary>
        /// Property countryLetterCode
        /// </summary>
        CountryLetterCode = 19,

        /// <summary>
        /// Property department
        /// </summary>
        Department = 20,

        /// <summary>
        /// Property description
        /// </summary>
        Description = 21,

        /// <summary>
        /// Property deviceId
        /// </summary>
        DeviceId = 22,

        /// <summary>
        /// Property deviceObjectVersion
        /// </summary>
        DeviceObjectVersion = 23,

        /// <summary>
        /// Property deviceOSType
        /// </summary>
        DeviceOSType = 24,

        /// <summary>
        /// Property deviceOSVersion
        /// </summary>
        DeviceOSVersion = 25,

        /// <summary>
        /// Property devicePhysicalIds
        /// </summary>
        DevicePhysicalIds = 26,

        /// <summary>
        /// Property dirSyncEnabled
        /// </summary>
        DirSyncEnabled = 27,

        /// <summary>
        /// Property displayName
        /// </summary>
        DisplayName = 28,

        /// <summary>
        /// Property errorUrl
        /// </summary>
        ErrorUrl = 29,

        /// <summary>
        /// Property expiryTime
        /// </summary>
        ExpiryTime = 30,

        /// <summary>
        /// Property facsimileTelephoneNumber
        /// </summary>
        FacsimileTelephoneNumber = 31,

        /// <summary>
        /// Property givenName
        /// </summary>
        GivenName = 32,

        /// <summary>
        /// Property homepage
        /// </summary>
        Homepage = 33,

        /// <summary>
        /// Property identifierUris
        /// </summary>
        IdentifierUris = 34,

        /// <summary>
        /// Property immutableId
        /// </summary>
        ImmutableId = 35,

        /// <summary>
        /// Property isSystem
        /// </summary>
        IsSystem = 36,

        /// <summary>
        /// Property jobTitle
        /// </summary>
        JobTitle = 37,

        /// <summary>
        /// Property keyCredentials
        /// </summary>
        KeyCredentials = 38,

        /// <summary>
        /// Property lastDirSyncTime
        /// </summary>
        LastDirSyncTime = 39,

        /// <summary>
        /// Property logoutUrl
        /// </summary>
        LogoutUrl = 40,

        /// <summary>
        /// Property mail
        /// </summary>
        Mail = 41,

        /// <summary>
        /// Property mailEnabled
        /// </summary>
        MailEnabled = 42,

        /// <summary>
        /// Property mailNickname
        /// </summary>
        MailNickname = 43,

        /// <summary>
        /// Property mainLogo
        /// </summary>
        MainLogo = 44,

        /// <summary>
        /// Property marketingNotificationEmails
        /// </summary>
        MarketingNotificationEmails = 45,

        /// <summary>
        /// Property maximumRegistrationInactivityPeriod
        /// </summary>
        MaximumRegistrationInactivityPeriod = 46,

        /// <summary>
        /// Property mobile
        /// </summary>
        Mobile = 47,

        /// <summary>
        /// Property objectId
        /// </summary>
        ObjectId = 48,

        /// <summary>
        /// Property objectType
        /// </summary>
        ObjectType = 49,

        /// <summary>
        /// Property otherMails
        /// </summary>
        OtherMails = 50,

        /// <summary>
        /// Property passwordCredentials
        /// </summary>
        PasswordCredentials = 51,

        /// <summary>
        /// Property passwordPolicies
        /// </summary>
        PasswordPolicies = 52,

        /// <summary>
        /// Property passwordProfile
        /// </summary>
        PasswordProfile = 53,

        /// <summary>
        /// Property physicalDeliveryOfficeName
        /// </summary>
        PhysicalDeliveryOfficeName = 54,

        /// <summary>
        /// Property postalCode
        /// </summary>
        PostalCode = 55,

        /// <summary>
        /// Property preferredLanguage
        /// </summary>
        PreferredLanguage = 56,

        /// <summary>
        /// Property prepaidUnits
        /// </summary>
        PrepaidUnits = 57,

        /// <summary>
        /// Property principalId
        /// </summary>
        PrincipalId = 58,

        /// <summary>
        /// Property provisionedPlans
        /// </summary>
        ProvisionedPlans = 59,

        /// <summary>
        /// Property provisioningErrors
        /// </summary>
        ProvisioningErrors = 60,

        /// <summary>
        /// Property proxyAddresses
        /// </summary>
        ProxyAddresses = 61,

        /// <summary>
        /// Property publicClient
        /// </summary>
        PublicClient = 62,

        /// <summary>
        /// Property publicIssuerCertificates
        /// </summary>
        PublicIssuerCertificates = 63,

        /// <summary>
        /// Property publisherName
        /// </summary>
        PublisherName = 64,

        /// <summary>
        /// Property registrationQuota
        /// </summary>
        RegistrationQuota = 65,

        /// <summary>
        /// Property replyUrls
        /// </summary>
        ReplyUrls = 66,

        /// <summary>
        /// Property resourceId
        /// </summary>
        ResourceId = 67,

        /// <summary>
        /// Property roleDisabled
        /// </summary>
        RoleDisabled = 68,

        /// <summary>
        /// Property samlMetadataUrl
        /// </summary>
        SamlMetadataUrl = 69,

        /// <summary>
        /// Property scope
        /// </summary>
        Scope = 70,

        /// <summary>
        /// Property securityEnabled
        /// </summary>
        SecurityEnabled = 71,

        /// <summary>
        /// Property servicePlans
        /// </summary>
        ServicePlans = 72,

        /// <summary>
        /// Property servicePrincipalNames
        /// </summary>
        ServicePrincipalNames = 73,

        /// <summary>
        /// Property skuId
        /// </summary>
        SkuId = 74,

        /// <summary>
        /// Property skuPartNumber
        /// </summary>
        SkuPartNumber = 75,

        /// <summary>
        /// Property sourceObjectId
        /// </summary>
        SourceObjectId = 76,

        /// <summary>
        /// Property sourceObjectType
        /// </summary>
        SourceObjectType = 77,

        /// <summary>
        /// Property sourceObjectUri
        /// </summary>
        SourceObjectUri = 78,

        /// <summary>
        /// Property startTime
        /// </summary>
        StartTime = 79,

        /// <summary>
        /// Property state
        /// </summary>
        State = 80,

        /// <summary>
        /// Property street
        /// </summary>
        Street = 81,

        /// <summary>
        /// Property streetAddress
        /// </summary>
        StreetAddress = 82,

        /// <summary>
        /// Property surname
        /// </summary>
        Surname = 83,

        /// <summary>
        /// Property tags
        /// </summary>
        Tags = 84,

        /// <summary>
        /// Property targetObjectId
        /// </summary>
        TargetObjectId = 85,

        /// <summary>
        /// Property targetObjectType
        /// </summary>
        TargetObjectType = 86,

        /// <summary>
        /// Property targetObjectUri
        /// </summary>
        TargetObjectUri = 87,

        /// <summary>
        /// Property technicalNotificationMails
        /// </summary>
        TechnicalNotificationMails = 88,

        /// <summary>
        /// Property telephoneNumber
        /// </summary>
        TelephoneNumber = 89,

        /// <summary>
        /// Property tenantType
        /// </summary>
        TenantType = 90,

        /// <summary>
        /// Property thumbnailPhoto
        /// </summary>
        ThumbnailPhoto = 91,

        /// <summary>
        /// Property usageLocation
        /// </summary>
        UsageLocation = 92,

        /// <summary>
        /// Property userPrincipalName
        /// </summary>
        UserPrincipalName = 93,

        /// <summary>
        /// Property userType
        /// </summary>
        UserType = 94,

        /// <summary>
        /// Property verifiedDomains
        /// </summary>
        VerifiedDomains = 95,
    }
}
