//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Azure.ActiveDirectory.GraphClient
{
    using System;

    /// <summary>
    /// Enumeration of link names.
    /// </summary>
    public enum LinkProperty
    {
        /// <summary>
        /// Property None
        /// </summary>
        None = 0,

        /// <summary>
        /// Property createdObjects
        /// </summary>
        CreatedObjects = 1,

        /// <summary>
        /// Property createdOnBehalfOf
        /// </summary>
        CreatedOnBehalfOf = 2,

        /// <summary>
        /// Property directReports
        /// </summary>
        DirectReports = 3,

        /// <summary>
        /// Property manager
        /// </summary>
        Manager = 4,

        /// <summary>
        /// Property memberOf
        /// </summary>
        MemberOf = 5,

        /// <summary>
        /// Property members
        /// </summary>
        Members = 6,

        /// <summary>
        /// Property ownedDevices
        /// </summary>
        OwnedDevices = 7,

        /// <summary>
        /// Property ownedObjects
        /// </summary>
        OwnedObjects = 8,

        /// <summary>
        /// Property owners
        /// </summary>
        Owners = 9,

        /// <summary>
        /// Property permissions
        /// </summary>
        Permissions = 10,

        /// <summary>
        /// Property registeredDevices
        /// </summary>
        RegisteredDevices = 11,

        /// <summary>
        /// Property registeredOwners
        /// </summary>
        RegisteredOwners = 12,

        /// <summary>
        /// Property registeredUsers
        /// </summary>
        RegisteredUsers = 13,
    }
}
