//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Azure.ActiveDirectory.GraphClient
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Stores a map of link attribute name on the proxy to the name on the server.
    /// </summary>
    public partial class LinkNameMap
    {
        /// <summary>
        /// Link name map
        /// </summary>
        public static List<string> NameMap = new List<string>()
            {
                { "none" },
                { "createdObjects" },
                { "createdOnBehalfOf" },
                { "directReports" },
                { "manager" },
                { "memberOf" },
                { "members" },
                { "ownedDevices" },
                { "ownedObjects" },
                { "owners" },
                { "permissions" },
                { "registeredDevices" },
                { "registeredOwners" },
                { "registeredUsers" },
            };
    }
}
