//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Azure.ActiveDirectory.GraphClient
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Stores a map of property name on the proxy to the name on the server.
    /// </summary>
    public partial class PropertyNameMap
    {
        /// <summary>
        /// Property name map.
        /// </summary>
        public static List<string> NameMap = new List<string>()
            {
                { "none" },
                { "accountEnabled" },
                { "alternativeSecurityIds" },
                { "appId" },
                { "appOwnerTenantId" },
                { "approximateLastLogonTimestamp" },
                { "assignedLicenses" },
                { "assignedPlans" },
                { "associationType" },
                { "authenticationPolicy" },
                { "availableToOtherTenants" },
                { "capabilityStatus" },
                { "city" },
                { "clientId" },
                { "cloudPublicIssuerCertificates" },
                { "companyLastDirSyncTime" },
                { "consentType" },
                { "consumedUnits" },
                { "country" },
                { "countryLetterCode" },
                { "department" },
                { "description" },
                { "deviceId" },
                { "deviceObjectVersion" },
                { "deviceOSType" },
                { "deviceOSVersion" },
                { "devicePhysicalIds" },
                { "dirSyncEnabled" },
                { "displayName" },
                { "errorUrl" },
                { "expiryTime" },
                { "facsimileTelephoneNumber" },
                { "givenName" },
                { "homepage" },
                { "identifierUris" },
                { "immutableId" },
                { "isSystem" },
                { "jobTitle" },
                { "keyCredentials" },
                { "lastDirSyncTime" },
                { "logoutUrl" },
                { "mail" },
                { "mailEnabled" },
                { "mailNickname" },
                { "mainLogo" },
                { "marketingNotificationEmails" },
                { "maximumRegistrationInactivityPeriod" },
                { "mobile" },
                { "objectId" },
                { "objectType" },
                { "otherMails" },
                { "passwordCredentials" },
                { "passwordPolicies" },
                { "passwordProfile" },
                { "physicalDeliveryOfficeName" },
                { "postalCode" },
                { "preferredLanguage" },
                { "prepaidUnits" },
                { "principalId" },
                { "provisionedPlans" },
                { "provisioningErrors" },
                { "proxyAddresses" },
                { "publicClient" },
                { "publicIssuerCertificates" },
                { "publisherName" },
                { "registrationQuota" },
                { "replyUrls" },
                { "resourceId" },
                { "roleDisabled" },
                { "samlMetadataUrl" },
                { "scope" },
                { "securityEnabled" },
                { "servicePlans" },
                { "servicePrincipalNames" },
                { "skuId" },
                { "skuPartNumber" },
                { "sourceObjectId" },
                { "sourceObjectType" },
                { "sourceObjectUri" },
                { "startTime" },
                { "state" },
                { "street" },
                { "streetAddress" },
                { "surname" },
                { "tags" },
                { "targetObjectId" },
                { "targetObjectType" },
                { "targetObjectUri" },
                { "technicalNotificationMails" },
                { "telephoneNumber" },
                { "tenantType" },
                { "thumbnailPhoto" },
                { "usageLocation" },
                { "userPrincipalName" },
                { "userType" },
                { "verifiedDomains" },
            };
    }
}
